#!/bin/bash
# sync.sh — Sincroniza las tablas Auto-invoke en AGENTS.md
# Uso: ./skills/skill-sync/assets/sync.sh [--dry-run]

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
REPO_ROOT="$(dirname "$SKILLS_DIR")"
AGENTS_MD="$REPO_ROOT/AGENTS.md"

DRY_RUN=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--dry-run]"
            echo "  --dry-run    Show what would change without modifying files"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

echo -e "${BLUE}Syncing Auto-invoke tables to AGENTS.md...${NC}"

if [ ! -f "$AGENTS_MD" ]; then
    echo -e "${RED}Error: AGENTS.md not found at $AGENTS_MD${NC}"
    exit 1
fi

# Temporary file for building the table
TEMP_TABLE=$(mktemp)
trap "rm -f $TEMP_TABLE" EXIT

# Find all SKILL.md files and extract auto_invoke metadata
while IFS= read -r skill_file; do
    skill_dir=$(dirname "$skill_file")
    skill_name=$(basename "$skill_dir")
    
    # Skip skill-sync itself from the main table (it's meta)
    if [ "$skill_name" = "skill-sync" ]; then
        continue
    fi
    
    # Extract auto_invoke from YAML frontmatter using awk
    # This handles both single string and array formats
    in_frontmatter=false
    in_auto_invoke=false
    
    while IFS= read -r line; do
        if [[ "$line" == "---" ]]; then
            if [ "$in_frontmatter" = true ]; then
                break
            fi
            in_frontmatter=true
            continue
        fi
        
        if [ "$in_frontmatter" = true ]; then
            # Check if we're entering auto_invoke
            if [[ "$line" =~ ^[[:space:]]*auto_invoke: ]]; then
                in_auto_invoke=true
                # Check if it's a single-line value
                value=$(echo "$line" | sed 's/.*auto_invoke:[[:space:]]*//' | sed 's/^"//' | sed 's/"$//')
                if [ -n "$value" ] && [[ ! "$value" =~ ^\| ]] && [[ ! "$value" =~ ^\> ]]; then
                    echo -e "${value}\t${skill_name}" >> "$TEMP_TABLE"
                fi
                continue
            fi
            
            # If we're in auto_invoke and line starts with "- "
            if [ "$in_auto_invoke" = true ]; then
                if [[ "$line" =~ ^[[:space:]]*-[[:space:]]+ ]]; then
                    action=$(echo "$line" | sed 's/^[[:space:]]*-[[:space:]]*//' | sed 's/^"//' | sed 's/"$//')
                    echo -e "${action}\t${skill_name}" >> "$TEMP_TABLE"
                elif [[ "$line" =~ ^[[:space:]]*[a-zA-Z_]+: ]]; then
                    # New field started, exit auto_invoke
                    in_auto_invoke=false
                fi
            fi
        fi
    done < "$skill_file"
    
done < <(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name "SKILL.md" -print | sort)

# Sort the table by action (first column)
SORTED_TABLE=$(sort -t$'\t' -k1 "$TEMP_TABLE")

# Build the markdown table
AUTO_INVOKE_SECTION="### Auto-invoke Skills

When performing these actions, ALWAYS invoke the corresponding skill FIRST:

| Action | Skill |
|--------|-------|"

while IFS=$'\t' read -r action skill; do
    if [ -n "$action" ] && [ -n "$skill" ]; then
        AUTO_INVOKE_SECTION="${AUTO_INVOKE_SECTION}
| ${action} | \`${skill}\` |"
    fi
done <<< "$SORTED_TABLE"

# Add closing note
AUTO_INVOKE_SECTION="${AUTO_INVOKE_SECTION}

<!-- AUTO-GENERATED by sync.sh. Do not edit manually. -->"

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY RUN] Would update AGENTS.md with:${NC}"
    echo ""
    echo "$AUTO_INVOKE_SECTION"
    echo ""
else
    # Replace the Auto-invoke section in AGENTS.md
    # Use awk to find and replace the section
    awk -v new_section="$AUTO_INVOKE_SECTION" '
    BEGIN { in_section = 0; printed = 0 }
    /^### Auto-invoke Skills/ {
        in_section = 1
        print new_section
        printed = 1
        next
    }
    in_section && /^### / && !/^### Auto-invoke Skills/ {
        in_section = 0
    }
    in_section && /^## / {
        in_section = 0
    }
    in_section && /^---$/ {
        in_section = 0
    }
    !in_section { print }
    END {
        if (!printed) {
            print ""
            print new_section
        }
    }
    ' "$AGENTS_MD" > "${AGENTS_MD}.tmp" && mv "${AGENTS_MD}.tmp" "$AGENTS_MD"
    
    echo -e "${GREEN}✓ Updated Auto-invoke section in AGENTS.md${NC}"
fi

# Count skills processed
skill_count=$(echo "$SORTED_TABLE" | grep -c . || echo "0")
echo -e "${BLUE}Processed ${skill_count} auto-invoke entries from skills.${NC}"
